# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

module(name = "score_cpp_policies_tests")

bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "toolchains_llvm", version = "1.7.0")
bazel_dep(name = "score_bazel_platforms", version = "1.0.0")
bazel_dep(name = "score_cpp_policies")
local_path_override(
    module_name = "score_cpp_policies",
    path = "..",
)

# --- GCC toolchain ---

bazel_dep(name = "score_bazel_cpp_toolchains", version = "1.0.2")
gcc = use_extension("@score_bazel_cpp_toolchains//extensions:gcc.bzl", "gcc")
gcc.toolchain(
    name = "score_gcc_x86_64_toolchain_fi",
    extra_known_features = [
        "@score_cpp_policies//sanitizers/features:debug_symbols",
        "@score_cpp_policies//sanitizers/features:asan",
        "@score_cpp_policies//sanitizers/features:ubsan_base",
        "@score_cpp_policies//sanitizers/features:ubsan_gcc",
        "@score_cpp_policies//sanitizers/features:lsan",
        "@score_cpp_policies//sanitizers/features:tsan",
    ],
    target_cpu = "x86_64",
    target_os = "linux",
    use_base_constraints_only = True,
    use_default_package = True,
    version = "12.2.0",
)
gcc.toolchain(
    name = "score_gcc_toolchain_15",
    extra_known_features = [
        "@score_cpp_policies//warnings/gcc/features:minimal_warnings",
        "@score_cpp_policies//warnings/gcc/features:strict_warnings",
        "@score_cpp_policies//warnings/gcc/features:all_wall_warnings",
        "@score_cpp_policies//warnings/gcc/features:warnings_as_errors",
    ],
    target_cpu = "x86_64",
    target_os = "linux",
    use_default_package = True,
    version = "15.3.0",
)
use_repo(gcc, "score_gcc_x86_64_toolchain_fi", "score_gcc_toolchain_15")

# --- Clang toolchain ---

llvm = use_extension(
    "@toolchains_llvm//toolchain/extensions:llvm.bzl",
    "llvm",
)
llvm.toolchain(
    extra_known_features = [
        "@score_cpp_policies//sanitizers/features:debug_symbols",
        "@score_cpp_policies//sanitizers/features:asan",
        "@score_cpp_policies//sanitizers/features:ubsan_base",
        "@score_cpp_policies//sanitizers/features:ubsan_clang",
        "@score_cpp_policies//sanitizers/features:lsan",
        "@score_cpp_policies//sanitizers/features:tsan",
    ],
    llvm_version = "19.1.7",
)
use_repo(llvm, "llvm_toolchain")
